### PR TITLE
Fixes url for Company class

### PR DESCRIPTION
**Pull request by justJay-dev**
Fixed my commit history, this is a small change that corrects for the new safer url.

### CODE REVIEW

**Comment by novice39** [comment]
I'm a total Novice. How do I run a web scrape using this? Can someone dummy this down for a noob with windows 10?

**Comment by justJay-dev** [comment]
> I'm a total Novice. How do I run a web scrape using this? Can someone dummy this down for a noob with windows 10?

Hi Friend! You've posted this on a pull request, pull requests on github are used for developers to suggest changes to improve programs, if you add some of your social media or contact information in your profile, i'd be happy to reach out on some use-cases for this. Unfortunately, this is more of a toolkit and not a tool, but getting started isnt too hard!

**Comment by novice39** [comment]
Thank you!! I'll do that!

**Comment by novice39** [comment]
I put my Instagram up Jay and my email is public. Thank you sho much!

**Comment by arthurtyukayev** [comment]
@justJay-dev thanks for replying to @novice39.

**Pull request merged**
